name: CoinBukkit
version: ${project.version}
main: com.miketheshadow.coinbukkit.CoinBukkit
api-version: 1.13
authors: [MikeTheShadow]
description: Coin purse plugin for minecarft
depend: [ComplexProficiencies]
commands:
  openpurse:
    description: Opens a purse
    usage: /<openpurse> [rarity] [amount (optional)]
    permission: CoinBukkit.basic
    permission-message: You don't have CoinBukkit.basic permission
  purse:
    description: Check your balance
    usage: /<purse>
    permission: CoinBukkit.basic
    permission-message: You don't have CoinBukkit.basic permission
  purselist:
    description: List all purses you have
    usage: /<purselist>
    permission: CoinBukkit.basic
    permission-message: You don't have CoinBukkit.basic permission
  addpurse:
    description: Adds a purse to a player
    usage: /<addpurse> [level] [levelNum] [player]
    permission: CoinBukkit.admin
    permission-message: You don't have CoinBukkit.basic permission
  createpurse:
    description: Create a new purse
    usage: /<createpurse> [name] [maxLevel] [colorCode] [%chance] [minMoney] [maxMoney] [laborCost]
    permission: CoinBukkit.admin
    permission-message: You don't have CoinBukkit.admin permission
  removepurse:
    description: Removes a purse
    usage: /<removepurse> [name]
    permission: CoinBukkit.admin
    permission-message: You don't have CoinBukkit.admin permission